qsub scripts/dwbc.sh
qsub scripts/climo_native.sh
qsub scripts/climo_z.sh
qsub scripts/basin_reductions.sh
qsub scripts/moc.sh
qsub scripts/moc_sigma2.sh
qsub scripts/pht.sh
qsub scripts/aaiw_pv.sh
qsub scripts/enso.sh
qsub scripts/transports.sh
qsub scripts/surface.sh
qsub scripts/equatorial.sh
qsub scripts/ts_levels.sh
qsub scripts/stats.sh
qsub scripts/drift_thetao.sh
qsub scripts/rms_thetao.sh
qsub scripts/drift_so.sh
qsub scripts/rms_so.sh
qsub scripts/tao.sh
