import yaml, os
import subprocess
import shutil
from datetime import datetime

def cime_xmlquery(caseroot, varname):
    """run CIME's xmlquery for varname in the directory caseroot, return the value"""
    try:
        value = subprocess.check_output(
            ["./xmlquery", "-N", "--value", varname],
            stderr=subprocess.STDOUT,
            cwd=caseroot,
        )
    except subprocess.CalledProcessError:
        value = subprocess.check_output(
            ["./xmlquery", "--value", varname], stderr=subprocess.STDOUT, cwd=caseroot
        )
    return value.decode()

# Get current Linux user and date
user_name = os.getenv('USER', 'Unknown User')
current_date = datetime.now().strftime('%Y-%m-%d')

# Path to the YAML configuration file
yaml_path = '../diag_config.yml'

# Path for the output Markdown file
output_md_path = 'intro.md'

# Load the YAML file
with open(yaml_path, 'r') as yaml_file:
    diag_config = yaml.safe_load(yaml_file)

# Extract information from the YAML file
case = diag_config.get('Case', {})
caseroot = case.get('CASEROOT', 'Unknown CASEROOT')
try:
  case_name = cime_xmlquery(caseroot, 'CASE')
except:
  case_name = 'Unknown case name'

try:
  srcroot = cime_xmlquery(caseroot, 'SRCROOT')
except:
  srcroot = 'Unknown srcroot'

try:
  rundir = cime_xmlquery(caseroot, 'RUNDIR')
  source_path = str(rundir)+"/MOM_parameter_doc.all"
  destination_path = os.path.join(os.getcwd(), os.path.basename(source_path))
except:
  rundir = 'Unknown rundir'

try:
  shutil.copy(source_path, destination_path)
  print(f"File successfully copied to {destination_path}")
except Exception as e:
  print(f"Error: {e}")

ocn_diag_root = case.get('OCN_DIAG_ROOT', 'Unknown OCN_DIAG_ROOT')
sname = case.get('SNAME', 'Unknown SNAME')

averages = diag_config.get('Avg', {})
start_date = averages.get('start_date', 'Unknown start_date')
end_date = averages.get('end_date', 'Unknown end_date')

ocean_catalog = diag_config['oce_cat']

# Generate the content for the Markdown file
markdown_content = (
    f"# Ocean diagnostics for {sname}\n\n"
    f"Welcome to the OMWG diagnostics. This is a collection of notebooks and scripts used to diagnose MOM6 solutions conducted with CESM.\n"
    f"These diagnostics were created using [mom6-tools](https://github.com/NCAR/mom6-tools). For detailed guidance and additional information, please refer to the [documentation](https://mom6-tools.readthedocs.io/).\n\n"
    f"### Case details\n\n"
    f"- CASENAME: `{case_name}`\n"
    f"- CASEROOT: `{caseroot}`\n"
    f"- OCN_DIAG_ROOT: `{ocn_diag_root}`\n"
    f"- SRCROOT: `{srcroot}`\n"
    f"- SHORTNAME: `{sname}`\n\n"
    f"- [MOM_parameter_doc.all](MOM_parameter_doc.all)\n\n"
    f"### Dates used for averages\n"
    f"- start_date: `{start_date}`\n"
    f"- end_date: `{end_date}`\n\n"
    f"### Ocean Catalogs\n"
    f"- oce_cat: `{ocean_catalog}`\n"
    f"- [NCAR CGD Ocean Section Catalogs](https://ncar.github.io/oce-catalogs/)\n\n"
    f"### Diagnostics generated by\n"
    f"- User: `{user_name}`\n"
    f"- Date: `{current_date}`\n\n"
)

# Write the Markdown content to the output file
with open(output_md_path, 'w') as md_file:
    md_file.write(markdown_content)

print(f"Markdown file '{output_md_path}' generated successfully!")

